<?php

namespace FrontOffice\OptimusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends EntityRepository {

    public function getParicipationNotification($id, $event, $date) {
        $em = $this->getEntityManager();
        $qb = $em->createQuery("select p, e, u "
                        . "  from FrontOfficeOptimusBundle:Participation p "
                        . "LEFT JOIN p.event e "
                        . "LEFT JOIN p.participant u "
                        . "where u.id = :id and e = :event and p.datePaticipation < :date  "
                )
                ->setParameter('event', $event)
                ->setParameter('date', $date->format('Y-m-d H:i:s'))
                ->setParameter('id', $id);
        return $qb->getResult();
    }

}
