front_office_optimus_controller:
    resource: "@FrontOfficeOptimusBundle/Controller"
    type:  annotation
    prefix:   /

add_club:
    path:     /club/add
    defaults: { _controller: FrontOfficeOptimusBundle:Club:ajouterClub }