parameters:
#    front_office_optimus.example.class: FrontOffice\OptimusBundle\Example

services:
#    front_office_optimus.example:
#        class: %front_office_optimus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
