parameters:
#    front_office_optimus.example.class: FrontOffice\OptimusBundle\Example

services:
     kernel.listener.onCreateHistoryEvent:
        class: FrontOffice\OptimusBundle\EventListener\HistoryListener
        arguments:
            em: "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: front_event.after_event_register, method: onCreateHistoryEvent }
#    front_office_optimus.example:
#        class: %front_office_optimus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
