front_office_optimus_controller:
    resource: "@FrontOfficeUserBundle/Controller"
    type:  annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
user_index:
    path:     /
    defaults: { _controller: FrontOfficeUserBundle:User:index }