parameters:
#    front_office_user.example.class: FrontOffice\UserBundle\Example

services:
    FrontOffice_user_registration.form.type:
          class: FrontOffice\UserBundle\Form\Type\RegistrationFormType
          tags:
              - { name: form.type, alias: frontoffice_user_registration }
          arguments: [%fos_user.model.user.class%]
    
    fos_user.registration_listener:
        class: FrontOffice\UserBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }      
            
    kernel.listener.onCreateUserNotification:
        class: FrontOffice\UserBundle\EventListener\RegisterEntraineurListner
        arguments:
            em: "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: front_event.after_entraineur_register, method: onCreateUserNotification }       
            
            
     